const levels=[
  {name:'赤焰沙海',short:'沙漠',emoji:'🏜️',sky:'#ed9d65',ground:'#c4774e',accent:'#ffd26b',enemy:'砂岩暴龙',type:'BOSS',weak:'腹部核心',hp:850,diff:'入门'},
  {name:'亚马逊秘境',short:'雨林',emoji:'🌿',sky:'#4d9b7a',ground:'#245e55',accent:'#9ce49a',enemy:'藤蔓棘龙',type:'ELITE',weak:'背部花冠',hp:1180,diff:'进阶'},
  {name:'深蓝回廊',short:'大海',emoji:'🌊',sky:'#287ea1',ground:'#16495f',accent:'#77d6e8',enemy:'潮汐沧龙',type:'ELITE',weak:'鳃部晶核',hp:1500,diff:'挑战'},
  {name:'云端雪岭',short:'雪山',emoji:'🏔️',sky:'#7197b8',ground:'#3b5977',accent:'#d8f0f3',enemy:'冰脊霸王龙',type:'MYTHIC',weak:'头冠裂隙',hp:1900,diff:'困难'},
  {name:'时空遗迹',short:'终局',emoji:'🌀',sky:'#73578d',ground:'#352d4d',accent:'#f0c778',enemy:'远古暴君',type:'FINAL',weak:'胸口时核',hp:2500,diff:'终极'},
];
const heroes=[{name:'小飞',role:'空袭先锋',face:'🛩️',color:'#087f83',tool:'飞行背包',move:'降龙十八掌'},{name:'天天',role:'高空侦察',face:'🚁',color:'#b86b0b',tool:'救援钩爪',move:'独孤九剑'},{name:'阿奇',role:'地面指挥',face:'🐶',color:'#b83b27',tool:'汪汪盾牌',move:'乾坤大挪移'}];
const drops=[{name:'能量包',icon:'⚡',kind:'energy'},{name:'血包',icon:'✚',kind:'heal'},{name:'飞侠导弹',icon:'🚀',kind:'bomb'},{name:'冰晶护盾',icon:'❄️',kind:'shield'}];
const state={mode:'solo',level:0,selectedHero:0,playing:false,paused:false,muted:false,keys:{},heroX:180,targetX:null,heroY:0,velY:0,onGround:true,airMode:false,enemyX:820,enemyHp:0,enemyAction:0,enemyFacing:-1,party:[],active:0,combo:0,maxCombo:0,comboMeter:0,drops:[],dropCount:0,startedAt:0,shots:[],particles:[],ambient:[],fx:[],floaters:[],lastTick:0,enemyCooldown:0,spawnTimer:0,shield:0,resultRetry:false,heroAction:0,enemyHit:0,shake:0,worldTime:0};
const $=s=>document.querySelector(s);const canvas=$('#gameCanvas');const ctx=canvas.getContext('2d');
const audio={ctx:null,master:null,unlocked:false,unlock(){if(this.unlocked)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return;this.ctx=new C();this.master=this.ctx.createGain();this.master.gain.value=.16;this.master.connect(this.ctx.destination);this.ctx.resume();this.unlocked=true;},tone(freq,duration=.12,type='sine',volume=.5,slide=0){if(state.muted)return;this.unlock();if(!this.ctx||!this.master)return;const now=this.ctx.currentTime;const osc=this.ctx.createOscillator();const gain=this.ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,now);if(slide)osc.frequency.exponentialRampToValueAtTime(Math.max(35,freq+slide),now+duration);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(Math.max(.0001,volume),now+.012);gain.gain.exponentialRampToValueAtTime(.0001,now+duration);osc.connect(gain);gain.connect(this.master);osc.start(now);osc.stop(now+duration+.02);},noise(duration=.12,volume=.25){if(state.muted)return;this.unlock();if(!this.ctx||!this.master)return;const length=Math.floor(this.ctx.sampleRate*duration);const buffer=this.ctx.createBuffer(1,length,this.ctx.sampleRate);const data=buffer.getChannelData(0);for(let i=0;i<length;i++)data[i]=(Math.random()*2-1)*(1-i/length);const src=this.ctx.createBufferSource();const gain=this.ctx.createGain();gain.gain.setValueAtTime(volume,this.ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,this.ctx.currentTime+duration);src.buffer=buffer;src.connect(gain);gain.connect(this.master);src.start();},play(name){const sounds={click:()=>this.tone(420,.06,'sine',.16,90),jump:()=>{this.tone(300,.16,'triangle',.18,260);this.tone(620,.1,'sine',.1,120);},attack:()=>{this.tone(190,.1,'sawtooth',.2,260);this.noise(.07,.09);},skill:()=>{this.tone(240,.22,'sawtooth',.25,620);this.tone(520,.2,'triangle',.13,300);},hit:()=>{this.tone(110,.15,'square',.22,-35);this.noise(.1,.13);},enemy:()=>{this.tone(95,.22,'sawtooth',.2,-40);this.noise(.14,.14);},collect:()=>{this.tone(640,.08,'sine',.16,180);this.tone(920,.12,'sine',.12,130);},combo:()=>{this.tone(300,.12,'triangle',.18,220);this.tone(580,.2,'triangle',.16,420);this.tone(980,.24,'sine',.1,0);},clear:()=>{[523,659,784].forEach((n,i)=>setTimeout(()=>this.tone(n,.2,'triangle',.16),i*100));},fail:()=>{this.tone(180,.3,'sawtooth',.17,-80);this.tone(110,.35,'sine',.11,-30);}};sounds[name]?.();}};
function renderRoster(){ $('#roster').innerHTML=heroes.map((h,i)=>`<button class="hero-chip ${i===state.selectedHero?'active':''}" data-hero="${i}"><span class="hero-face">${h.face}</span><b>${h.name}</b><small>${h.role}</small></button>`).join(''); }
function renderMissions(){ $('#missionList').innerHTML=levels.map((l,i)=>`<button class="mission-item ${i===state.level?'active':''}" data-level="${i}"><span class="mission-num">0${i+1}</span><span class="mission-emoji">${l.emoji}</span><span class="mission-name">${l.short}</span><span class="mission-diff">${l.diff}</span></button>`).join(''); }
renderRoster();renderMissions();
document.querySelectorAll('.mode-card').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.mode-card').forEach(b=>b.classList.remove('active'));btn.classList.add('active');state.mode=btn.dataset.mode;renderRoster();});
$('#roster').onclick=e=>{const card=e.target.closest('.hero-chip');if(!card)return;state.selectedHero=+card.dataset.hero;document.querySelectorAll('.hero-chip').forEach(c=>c.classList.toggle('active',c===card));};
$('#missionList').onclick=e=>{const item=e.target.closest('.mission-item');if(!item)return;state.level=+item.dataset.level;document.querySelectorAll('.mission-item').forEach(i=>i.classList.toggle('active',i===item));$('#radarThreat').textContent=`${levels[state.level].enemy.toUpperCase()} / 0${state.level+1}`;};
$('#launchBtn').onclick=()=>{audio.unlock();audio.play('click');startGame();};$('#backLobby').onclick=()=>{audio.play('click');stopGame();$('#gameView').classList.add('hidden');$('#lobbyView').classList.remove('hidden');};$('#pauseBtn').onclick=()=>{audio.play('click');state.paused=!state.paused;$('#pauseBtn').textContent=state.paused?'▶':'Ⅱ';showToast(state.paused?'任务暂停':'继续任务');};$('#soundToggle').onclick=()=>{state.muted=!state.muted;$('#soundToggle').textContent=state.muted?'♩':'♫';$('#soundToggle').title=state.muted?'开启声效':'关闭声效';if(!state.muted){audio.unlock();audio.play('click');}showToast(state.muted?'声效已关闭':'声效已开启');};$('#resultLobby').onclick=()=>{$('#resultModal').classList.add('hidden');stopGame();$('#gameView').classList.add('hidden');$('#lobbyView').classList.remove('hidden');};$('#nextMission').onclick=()=>{ audio.play('click');$('#resultModal').classList.add('hidden'); if(state.resultRetry){state.resultRetry=false;startGame();return;} if(state.level<4){state.level++;document.querySelectorAll('.mission-item').forEach((i,n)=>i.classList.toggle('active',n===state.level));startGame();}else{stopGame();$('#gameView').classList.add('hidden');$('#lobbyView').classList.remove('hidden');}};
function share(){const url=`${location.href.split('#')[0]}#mission=${state.level+1}&mode=${state.mode}`;if(navigator.clipboard){navigator.clipboard.writeText(url).then(()=>showToast('试玩链接已复制')).catch(()=>fallbackCopy(url));}else{fallbackCopy(url);}}function fallbackCopy(url){const box=document.createElement('textarea');box.value=url;box.style.position='fixed';box.style.opacity='0';document.body.appendChild(box);box.select();try{document.execCommand('copy');showToast('试玩链接已复制');}catch(e){window.prompt('复制下面的试玩链接',url);}box.remove();}$('#shareTop').onclick=share;$('#shareGame').onclick=share;
function startGame(){audio.unlock();audio.play('click');const l=levels[state.level];state.playing=true;state.paused=false;state.enemyHp=l.hp;state.heroX=180;state.targetX=null;state.heroY=0;state.velY=0;state.onGround=true;state.airMode=false;state.enemyX=820;state.enemyAction=0;state.enemyFacing=-1;state.combo=0;state.maxCombo=0;state.comboMeter=0;state.dropCount=0;state.drops=[];state.shots=[];state.particles=[];state.ambient=[];state.fx=[];state.floaters=[];state.shield=0;state.active=state.selectedHero;state.heroAction=0;state.enemyHit=0;state.shake=0;state.worldTime=0;state.startedAt=performance.now();state.lastTick=performance.now();state.spawnTimer=0;state.party=heroes.map((h,i)=>({hp:100,max:100,alive:state.mode==='squad'||i===state.selectedHero}));for(let i=0;i<35;i++)state.ambient.push({x:Math.random()*canvas.width,y:Math.random()*canvas.height*.78,vx:(Math.random()-.5)*.25,vy:(Math.random()-.5)*.12,life:100+Math.random()*160});$('#lobbyView').classList.add('hidden');$('#gameView').classList.remove('hidden');$('#levelLabel').textContent=String(state.level+1).padStart(2,'0');$('#levelName').textContent=l.name;$('#enemyName').textContent=l.enemy;$('#enemyType').textContent=l.type;$('#enemyLevel').textContent=`LV. 0${state.level+1}`;$('#enemyWeakness').textContent=l.weak;$('#bossBanner').classList.remove('hidden');setTimeout(()=>$('#bossBanner').classList.add('hidden'),1800);log(`进入${l.name}，目标：${l.enemy}`);updateHud();requestAnimationFrame(loop);}
function stopGame(){state.playing=false;state.paused=false;}
function loop(now){if(!state.playing)return;const dt=Math.min(32,now-state.lastTick)/16.67;state.lastTick=now;if(!state.paused){update(dt);draw();}requestAnimationFrame(loop);}
function update(dt){const k=state.keys;state.worldTime+=dt;state.heroAction=Math.max(0,state.heroAction-dt);state.enemyHit=Math.max(0,state.enemyHit-dt);state.enemyAction=Math.max(0,state.enemyAction-dt);state.shake=Math.max(0,state.shake-dt);const speed=4.4*(k.shift?1.25:1);if(k.a||k.ArrowLeft)state.heroX-=speed*dt;if(k.d||k.ArrowRight)state.heroX+=speed*dt;if(state.targetX!==null&&!k.a&&!k.d&&!k.ArrowLeft&&!k.ArrowRight){const distance=state.targetX-state.heroX;if(Math.abs(distance)>4)state.heroX+=Math.sign(distance)*Math.min(Math.abs(distance),speed*1.35*dt);else state.targetX=null;}state.heroX=Math.max(55,Math.min(canvas.width-185,state.heroX));if((k.w||k.ArrowUp)&&state.onGround){state.velY=-10;state.onGround=false;state.airMode=true;state.fx.push({type:'jump',x:state.heroX,y:canvas.height-105,life:14,max:14});}if((k.w||k.ArrowUp)&&!state.onGround){state.airMode=true;state.velY=Math.max(state.velY-.28*dt,-4.4);}if(k.s||k.ArrowDown)state.velY+=.35*dt;state.velY+=state.airMode?0.18*dt:.55*dt;state.heroY+=state.velY*dt;if(state.heroY>0){state.heroY=0;state.velY=0;state.onGround=true;state.airMode=false}if(k.j&&!state._j){attack(false);state._j=true}if(!k.j)state._j=false;if(k.k&&!state._k){attack(true);state._k=true}if(!k.k)state._k=false;if(k.l&&!state._l&&state.mode==='squad'){switchHero();state._l=true}if(!k.l)state._l=false;if(k[' ']&&!state._space){teamCombo();state._space=true}if(!k[' '])state._space=false;const enemyDistance=state.heroX-state.enemyX;if(Math.abs(enemyDistance)>260&&state.enemyHp>0){state.enemyX+=Math.sign(enemyDistance)*Math.min(Math.abs(enemyDistance)-260,(1.2+state.level*.15)*dt);}state.enemyFacing=state.heroX>=state.enemyX?1:-1;state.enemyCooldown-=dt;state.spawnTimer-=dt;if(state.enemyCooldown<=0&&Math.abs(state.enemyX-state.heroX)<390){enemyAttack();state.enemyCooldown=48-state.level*3}if(state.spawnTimer<=0&&state.enemyHp>0){spawnDrop();state.spawnTimer=100+Math.random()*130}if(Math.random()<.08*dt)state.ambient.push({x:Math.random()*canvas.width,y:Math.random()*canvas.height*.75,vx:(Math.random()-.5)*.25,vy:(Math.random()-.5)*.12,life:90+Math.random()*150});state.ambient.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt});state.ambient=state.ambient.filter(p=>p.life>0&&p.x>-20&&p.x<canvas.width+20);state.shots.forEach(s=>{s.x+=s.vx*dt;s.life-=dt});state.shots=state.shots.filter(s=>s.life>0&&s.x<canvas.width+20);state.particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=.12*dt;p.life-=dt});state.particles=state.particles.filter(p=>p.life>0);state.fx.forEach(f=>{f.life-=dt;});state.fx=state.fx.filter(f=>f.life>0);state.floaters.forEach(f=>{f.y-=.65*dt;f.life-=dt});state.floaters=state.floaters.filter(f=>f.life>0);state.drops.forEach(d=>{d.x-=.3*dt;d.life-=dt;if(Math.abs(d.x-state.heroX)<45&&Math.abs(d.y-(canvas.height-118-state.heroY))<65&&d.life>0){collectDrop(d)}});state.drops=state.drops.filter(d=>d.life>0);if(state.enemyHp<=0){completeLevel();}updateHud();}
function attack(special){if(state.enemyHp<=0)return;audio.play(special?'skill':'attack');const h=heroes[state.active];const range=special?500:310;const dist=Math.abs(state.enemyX-state.heroX);state.heroAction=special?18:11;state.fx.push({type:special?'ultimate':'slash',x:state.heroX+54,y:canvas.height-145+state.heroY,life:special?18:12,max:special?18:12,dir:state.enemyX>=state.heroX?1:-1});if(dist<range){let damage=(special?95:28)*(state.mode==='squad'?1.08:1);if(state.shield>0)damage*=1.15;state.enemyHp=Math.max(0,state.enemyHp-damage);state.combo++;state.maxCombo=Math.max(state.maxCombo,state.combo);state.comboMeter=Math.min(100,state.comboMeter+(special?30:12));state.enemyHit=12;state.shake=special?8:4;audio.play('hit');burst(state.enemyX,canvas.height-140, special?'#f2bf50':'#ffb18f',special?18:8);state.floaters.push({x:state.enemyX,y:canvas.height-188,text:`-${Math.round(damage)}`,color:special?'#ffe08a':'#fff',life:34,max:34});log(`${h.name} · ${special?h.move:'工具连击'} -${Math.round(damage)}`);showToast(special?`${h.move} 命中！`:'命中目标');}else{state.combo=0;log('攻击落空，重新靠近目标');}}
function teamCombo(){if(state.mode!=='squad')return showToast('切换至全员协作后可释放合击');if(state.enemyHp<=0)return;audio.play('combo');const damage=185+state.combo*5;state.enemyHp=Math.max(0,state.enemyHp-damage);state.comboMeter=100;state.combo+=3;state.maxCombo=Math.max(state.maxCombo,state.combo);state.enemyHit=20;state.shake=12;state.fx.push({type:'team',x:(state.heroX+state.enemyX)/2,y:canvas.height-170,life:26,max:26});burst(state.enemyX,canvas.height-150,'#71e3d2',30);state.floaters.push({x:state.enemyX,y:canvas.height-205,text:`合击 -${damage}`,color:'#9ff6e7',life:42,max:42});log('全员协作 · 飞侠导弹 + 汪汪盾阵');showToast('合击成功！伤害提升');}
function enemyAttack(){const targets=state.party.filter(p=>p.alive);if(!targets.length)return;audio.play('enemy');const dmg=7+state.level*2;const i=state.mode==='solo'?state.active:Math.floor(Math.random()*state.party.length);const p=state.party[i];if(!p?.alive)return;p.hp=Math.max(0,p.hp-dmg);state.combo=0;state.shake=6;state.fx.push({type:'enemy',x:state.heroX+20,y:canvas.height-148+state.heroY,life:16,max:16});$('#damageFlash').classList.remove('active');void $('#damageFlash').offsetWidth;$('#damageFlash').classList.add('active');state.floaters.push({x:state.heroX,y:canvas.height-185,text:`-${dmg}`,color:'#ffad91',life:28,max:28});log(`${heroes[i].name} 受到${dmg}点冲撞伤害`);if(p.hp<=0){p.alive=false;log(`${heroes[i].name} 暂时撤离`);if(state.mode==='solo')setTimeout(()=>endGame(false),500);}}
function spawnDrop(){const d=drops[Math.floor(Math.random()*drops.length)];state.drops.push({x:canvas.width+20,y:canvas.height-120-Math.random()*110,life:260,...d});}
function collectDrop(d){d.life=0;state.dropCount++;if(d.kind==='heal'){state.party.forEach(p=>{if(p.alive)p.hp=Math.min(p.max,p.hp+28)});showToast('血包：全队恢复 28 HP');log('拾取血包，全队恢复');}if(d.kind==='energy'){state.comboMeter=Math.min(100,state.comboMeter+35);showToast('能量包：合击能量 +35');log('拾取能量包');}if(d.kind==='bomb'){state.enemyHp=Math.max(0,state.enemyHp-85);burst(state.enemyX,canvas.height-150,'#ff784d',22);showToast('飞侠导弹：造成 85 伤害');log('使用飞侠导弹');}if(d.kind==='shield'){state.shield=120;showToast('冰晶护盾：攻击力提升');log('冰晶护盾已激活');}}
function switchHero(){let next=(state.active+1)%heroes.length;for(let i=0;i<heroes.length;i++){const idx=(next+i)%heroes.length;if(state.party[idx]?.alive){state.active=idx;showToast(`切换至 ${heroes[idx].name}`);log(`换位：${heroes[idx].name} 接管前线`);return;}}}
function completeLevel(){state.playing=false;state.resultRetry=false;const t=Math.round((performance.now()-state.startedAt)/1000);$('#resultBadge').textContent='CLEAR';$('#resultTitle').textContent=`${levels[state.level].name} 已清空`;$('#resultCopy').textContent=state.level<4?'救援信标重新上线，下一条航线已解锁。':'五个战区全部完成，恐龙威胁已解除。';$('#resultTime').textContent=`00:${String(t).padStart(2,'0')}`;$('#resultDrops').textContent=String(state.dropCount).padStart(2,'0');$('#resultCombo').textContent=String(state.maxCombo).padStart(2,'0');$('#nextMission').innerHTML=state.level<4?'下一关 <b>→</b>':'返回任务板 <b>↩</b>';$('#resultModal').classList.remove('hidden');}
function endGame(win){state.playing=false;state.resultRetry=true;$('#resultBadge').textContent='RETRY';$('#resultTitle').textContent='队伍需要重整';$('#resultCopy').textContent='别急，换一名队员或拾取血包再试一次。';$('#resultTime').textContent='--:--';$('#resultDrops').textContent=String(state.dropCount).padStart(2,'0');$('#resultCombo').textContent=String(state.maxCombo).padStart(2,'0');$('#nextMission').innerHTML='重新出发 <b>↻</b>';$('#resultModal').classList.remove('hidden');}
function updateHud(){const max=levels[state.level].hp;$('#enemyHp').style.width=`${Math.max(0,state.enemyHp/max*100)}%`;$('#enemyHpText').textContent=`${Math.ceil(state.enemyHp)} / ${max}`;$('#comboFill').style.width=`${state.comboMeter}%`;$('#comboCount').textContent=state.combo;$('#progressFill').style.width=`${Math.max(0,100-state.enemyHp/max*100)}%`;$('#progressText').textContent=`${Math.round(100-state.enemyHp/max*100)}%`;$('#partyHud').innerHTML=heroes.map((h,i)=>{const p=state.party[i]||{hp:0,alive:false};return `<div class="party-card ${i===state.active?'active':''} ${p.alive?'':'dead'}"><div class="party-card-head"><span class="party-avatar">${h.face}</span><span><h4>${h.name}</h4><small>${h.role}</small></span></div><div class="hp-track"><div class="hp-fill" style="width:${p.hp}%"></div></div></div>`}).join('');$('#toolHud').innerHTML=drops.slice(0,4).map(d=>`<div class="tool-item"><span>${d.icon}</span><small>${d.name}</small></div>`).join('');}
function showToast(t){const el=$('#toast');el.textContent=t;el.classList.remove('show');void el.offsetWidth;el.classList.add('show');}
function log(t){const el=$('#combatLog');const d=document.createElement('div');d.textContent=t;el.prepend(d);while(el.children.length>5)el.lastChild.remove();}
function burst(x,y,color,n){for(let i=0;i<n;i++)state.particles.push({x,y,vx:(Math.random()-.5)*8,vy:(Math.random()-.5)*8-2,life:25+Math.random()*20,color});}
function roundedRect(x,y,w,h,r,fill){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();}
function draw(){const l=levels[state.level];const w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);const sky=ctx.createLinearGradient(0,0,0,h);sky.addColorStop(0,l.sky);sky.addColorStop(1,l.ground);ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);ctx.save();if(state.shake>0){ctx.translate((Math.random()-.5)*state.shake,(Math.random()-.5)*state.shake*.65);}drawBackdrop(l,w,h);drawAmbient(w,h);ctx.fillStyle='#132b34aa';ctx.fillRect(0,h-96,w,96);ctx.fillStyle='#183c42';ctx.fillRect(0,h-98,w,10);drawDrops();drawHero(w,h);drawEnemy(w,h);drawFx(w,h);state.shots.forEach(s=>{ctx.fillStyle=s.color;ctx.shadowBlur=12;ctx.shadowColor=s.color;ctx.beginPath();ctx.arc(s.x,s.y,6,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;});state.particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life/35);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,4,4);});drawFloaters();ctx.restore();ctx.globalAlpha=1;}
function drawAmbient(w,h){state.ambient.forEach((p,i)=>{ctx.globalAlpha=Math.min(.45,p.life/120)*(.55+.45*Math.sin(state.worldTime/8+i));ctx.fillStyle=i%3===0?'#ffffff':'#d5ffec';ctx.beginPath();ctx.arc(p.x,p.y,1.5+(i%2),0,Math.PI*2);ctx.fill();});ctx.globalAlpha=1;}
function drawBackdrop(l,w,h){const parallax=(state.heroX*.08)%220;ctx.save();ctx.globalAlpha=.3;for(let i=-1;i<7;i++){const x=i*220-parallax;ctx.fillStyle=l.accent;ctx.beginPath();ctx.moveTo(x,h-98);ctx.lineTo(x+70,h-250-(i%3)*26);ctx.lineTo(x+220,h-98);ctx.fill();}ctx.globalAlpha=1;const detail=state.level;if(detail===0){ctx.fillStyle='#f9cf7a88';for(let i=0;i<7;i++){const x=(i*190-parallax*.7);ctx.beginPath();ctx.arc(x+30,h-150,34,Math.PI,Math.PI*2);ctx.fill();ctx.fillRect(x+28,h-150,5,52);ctx.fillRect(x+6,h-132,48,4);}ctx.fillStyle='#fff2bf77';ctx.fillRect(0,90,w,2);}else if(detail===1){ctx.strokeStyle='#9ce49a99';ctx.lineWidth=5;for(let i=0;i<10;i++){const x=i*130-parallax;ctx.beginPath();ctx.moveTo(x,h-98);ctx.quadraticCurveTo(x+45,h-220,x+75,h-280);ctx.stroke();ctx.fillStyle='#3f8e67aa';ctx.beginPath();ctx.arc(x+78,h-270,28,0,Math.PI*2);ctx.fill();}ctx.fillStyle='#b8f2b355';ctx.fillRect(0,70,w,70);}else if(detail===2){ctx.fillStyle='#a7eaf255';for(let i=0;i<9;i++){const x=i*150-parallax;ctx.beginPath();ctx.arc(x,h-120,70,Math.PI,Math.PI*2);ctx.fill();}ctx.strokeStyle='#d6fbff66';ctx.lineWidth=2;for(let y=120;y<330;y+=42){ctx.beginPath();ctx.moveTo(0,y);ctx.quadraticCurveTo(w/2,y+18,w,y);ctx.stroke();}}else if(detail===3){ctx.fillStyle='#e6f6f7aa';for(let i=0;i<8;i++){const x=i*175-parallax;ctx.beginPath();ctx.moveTo(x,h-98);ctx.lineTo(x+90,h-350-(i%2)*50);ctx.lineTo(x+190,h-98);ctx.fill();}ctx.fillStyle='#ffffffaa';ctx.beginPath();ctx.arc(w-130,110,38,0,Math.PI*2);ctx.fill();}else{ctx.strokeStyle='#e7b6f788';ctx.lineWidth=2;for(let i=0;i<9;i++){const x=i*150-parallax;ctx.beginPath();ctx.arc(x+70,180,40+(i%2)*22,0,Math.PI*2);ctx.stroke();}ctx.fillStyle='#f0c77855';ctx.fillRect(0,105,w,3);}ctx.fillStyle='#ffffffaa';ctx.font='700 13px Inter';ctx.fillText(`${String(state.level+1).padStart(2,'0')} / ${l.name}`,24,30);ctx.fillStyle='#ffffff88';ctx.font='10px Inter';ctx.fillText('RESCUE BEACON ONLINE',24,48);ctx.restore();}
function drawHero(w,h){const hero=heroes[state.active];const x=state.heroX,y=h-115+state.heroY;ctx.save();ctx.translate(x,y);const action=state.heroAction;const lean=action?(.08+action/170):Math.sin(state.worldTime/12)*.015;ctx.rotate(lean);if(state.airMode){ctx.strokeStyle=hero.color;ctx.lineWidth=4;ctx.globalAlpha=.75;ctx.beginPath();ctx.moveTo(-30,20);ctx.lineTo(-58,34+Math.sin(state.worldTime/5)*5);ctx.moveTo(25,20);ctx.lineTo(52,34+Math.cos(state.worldTime/5)*5);ctx.stroke();ctx.globalAlpha=1;}if(action>3){ctx.globalAlpha=.18;ctx.fillStyle=hero.color;ctx.font='54px sans-serif';ctx.fillText(hero.face,-45,-5);ctx.globalAlpha=1;}ctx.fillStyle='#0004';ctx.beginPath();ctx.ellipse(25,25,45,9,0,0,Math.PI*2);ctx.fill();ctx.font='54px sans-serif';ctx.fillText(hero.face,-22,5);ctx.fillStyle=hero.color;ctx.fillRect(-13,9,53,7);ctx.fillStyle='#fff';ctx.font='800 12px Inter';ctx.fillText(hero.name,-18,-60);if(state.airMode){ctx.fillStyle='#d6fff2';ctx.font='800 10px Inter';ctx.fillText('AIR',18,-74);}if(state.shield>0){ctx.strokeStyle='#8eeae1';ctx.lineWidth=4;ctx.beginPath();ctx.arc(10,-18,45,0,Math.PI*2);ctx.stroke();}ctx.restore();}
function drawEnemy(w,h){const lunge=state.enemyAction?Math.sin((20-state.enemyAction)/20*Math.PI)*24*state.enemyFacing:0;const x=state.enemyX+lunge+(state.enemyHit?Math.sin(state.enemyHit*2)*7:0),y=h-123+(state.enemyHit?Math.sin(state.enemyHit*1.4)*3:0);ctx.save();ctx.translate(x,y);const bob=Math.sin(state.worldTime/18)*3;ctx.translate(0,bob);ctx.fillStyle='#0005';ctx.beginPath();ctx.ellipse(0,34,98,14,0,0,Math.PI*2);ctx.fill();if(state.enemyAction){ctx.strokeStyle='#ff9c77';ctx.lineWidth=7;ctx.globalAlpha=.7;ctx.beginPath();ctx.moveTo(-state.enemyFacing*30,-30);ctx.lineTo(-state.enemyFacing*90,-15);ctx.stroke();ctx.globalAlpha=1;}if(state.enemyHit){ctx.globalAlpha=.22;ctx.fillStyle='#ff8c6c';ctx.beginPath();ctx.arc(0,-28,82,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;}ctx.font=`${state.level===4?116:104}px sans-serif`;ctx.fillText('🦖',-66,22);ctx.fillStyle='#fff';ctx.font='800 13px Inter';ctx.textAlign='center';ctx.fillText(levels[state.level].enemy,0,-98);ctx.textAlign='left';ctx.restore();}
function drawDrops(){state.drops.forEach(d=>{ctx.save();const float=Math.sin((state.worldTime+d.x)/12)*4;ctx.translate(d.x,d.y+float);ctx.fillStyle='#ffffffdd';ctx.shadowColor='#9ff6e7';ctx.shadowBlur=14;ctx.beginPath();ctx.arc(0,0,18,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.font='20px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(d.icon,0,1);ctx.restore();});}
function drawFx(w,h){state.fx.forEach(f=>{const p=1-f.life/f.max;ctx.save();ctx.globalAlpha=Math.sin(Math.min(1,p)*Math.PI);if(f.type==='slash'||f.type==='ultimate'){ctx.translate(f.x,f.y);ctx.scale(f.dir||1,1);ctx.strokeStyle=f.type==='ultimate'?'#ffe07a':'#b9fff2';ctx.lineWidth=f.type==='ultimate'?12:7;ctx.shadowBlur=18;ctx.shadowColor=ctx.strokeStyle;ctx.beginPath();ctx.arc(0,0,f.type==='ultimate'?55+80*p:42+44*p,-.9,.9);ctx.stroke();if(f.type==='ultimate'){ctx.strokeStyle='#ff8a62';ctx.lineWidth=3;ctx.beginPath();ctx.arc(6,0,70+60*p,-.8,.8);ctx.stroke();}}else if(f.type==='team'){ctx.strokeStyle='#76efe0';ctx.lineWidth=5;ctx.shadowBlur=22;ctx.shadowColor='#76efe0';ctx.beginPath();ctx.arc(f.x,f.y,30+130*p,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#f9d17b';for(let i=0;i<8;i++){const a=i*Math.PI/4+p*2;ctx.fillRect(f.x+Math.cos(a)*(30+90*p),f.y+Math.sin(a)*(30+90*p),5,5);}}else if(f.type==='enemy'){ctx.strokeStyle='#ff886f';ctx.lineWidth=8;ctx.beginPath();ctx.arc(f.x,f.y,25+35*p,0,Math.PI*2);ctx.stroke();}else if(f.type==='jump'){ctx.strokeStyle='#a7eee3';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(f.x,f.y,24+24*p,7,0,0,Math.PI*2);ctx.stroke();}else if(f.type==='target'){ctx.strokeStyle='#ffffffcc';ctx.lineWidth=3;ctx.beginPath();ctx.arc(f.x,f.y,12+22*p,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(f.x-25,f.y);ctx.lineTo(f.x+25,f.y);ctx.moveTo(f.x,f.y-25);ctx.lineTo(f.x,f.y+25);ctx.stroke();}ctx.restore();});}
function drawFloaters(){state.floaters.forEach(f=>{ctx.save();ctx.globalAlpha=Math.min(1,f.life/12);ctx.fillStyle=f.color;ctx.font='800 16px Inter';ctx.textAlign='center';ctx.shadowColor='#092934';ctx.shadowBlur=5;ctx.fillText(f.text,f.x,f.y);ctx.restore();});}
window.addEventListener('keydown',e=>{state.keys[e.key]=true;if([' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))e.preventDefault();});window.addEventListener('keyup',e=>{state.keys[e.key]=false;});
canvas.addEventListener('click',e=>{if(!state.playing)return;const rect=canvas.getBoundingClientRect();state.targetX=Math.max(55,Math.min(canvas.width-185,(e.clientX-rect.left)*(canvas.width/rect.width)));state.fx.push({type:'target',x:state.targetX,y:canvas.height-102,life:24,max:24});});
document.querySelectorAll('.mouse-controls [data-control]').forEach(btn=>{const control=btn.dataset.control;const press=e=>{e.preventDefault();if(!state.playing)return;if(control==='left'||control==='right'){state.keys[control==='left'?'a':'d']=true;audio.play('click');}else if(control==='jump'){audio.play('jump');state.keys.w=true;}else if(control==='attack'){attack(false);}else if(control==='skill'){attack(true);}else if(control==='combo'){teamCombo();}};const release=e=>{e.preventDefault();if(control==='left'||control==='right')state.keys[control==='left'?'a':'d']=false;if(control==='jump')state.keys.w=false;};btn.addEventListener('pointerdown',press);btn.addEventListener('pointerup',release);btn.addEventListener('pointerleave',release);});
if(location.hash){const m=location.hash.match(/mission=(\d+)/);if(m){state.level=Math.max(0,Math.min(4,+m[1]-1));document.querySelectorAll('.mission-item').forEach((i,n)=>i.classList.toggle('active',n===state.level));}const mode=location.hash.match(/mode=(solo|squad)/);if(mode){state.mode=mode[1];document.querySelectorAll('.mode-card').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));}}

// Hook sound cues onto the existing actions without changing combat values.
const baseAttack=attack,baseTeamCombo=teamCombo,baseEnemyAttack=enemyAttack,baseCollectDrop=collectDrop,baseCompleteLevel=completeLevel,baseEndGame=endGame;
attack=function(special){baseAttack(special);};
teamCombo=function(){baseTeamCombo();};
enemyAttack=function(){state.enemyAction=20;baseEnemyAttack();};
collectDrop=function(drop){baseCollectDrop(drop);audio.play('collect');};
completeLevel=function(){audio.play('clear');baseCompleteLevel();};
endGame=function(win){audio.play('fail');baseEndGame(win);};
